#!/bin/bash

# Create an alias to run the instance.py file
echo "alias odoo-server-manager='python3 /etc/odoo-server-manager/src/instance.py'" >> ~/.bashrc
source ~/.bashrc || true  # Reload the shell configuration
