name: Build Debian Package

on:
  push:
    branches:
      - main  # Modify this according to your branch

jobs:
  build-deb-package:
    runs-on: ubuntu-latest  # Use the appropriate runner for your requirements

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debhelper dh-make dh-python

      - name: Update chmod of odoo-server-manager
        run: |
          chmod +x src/usr/bin/odoo-server-manager
      
      - name: Build package
        run: |
          dpkg-deb --build src

      - name: Rename package
        run: mv src.deb odoo-server-manager.deb

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: odoo-server-manager.deb
      